# Generated by Django 5.1.2 on 2024-11-27 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image7',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image8',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/product/'),
        ),
    ]
